version: '3.9'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: marcasautosdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: ./MarcasAutosAPI   
      dockerfile: Dockerfile  
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=marcasautosdb;Username=user;Password=password;Pooling=true;MinPoolSize=10;MaxPoolSize=100;Include Error Detail=true;"
    ports:
      - "5000:5000"
    depends_on:
      - postgres

volumes:
  postgres_data:
