// <auto-generated />
using MarcasAutosAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MarcasAutosAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250115214827_MigrationGenesis1")]
    partial class MigrationGenesis1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MarcasAutosAPI.Data.MarcaAuto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("MarcasAutos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Toyota"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Ford"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Chevrolet"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Honda"
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "Nissan"
                        },
                        new
                        {
                            Id = 6,
                            Nombre = "BMW"
                        },
                        new
                        {
                            Id = 7,
                            Nombre = "Mercedes-Benz"
                        },
                        new
                        {
                            Id = 8,
                            Nombre = "Volkswagen"
                        },
                        new
                        {
                            Id = 9,
                            Nombre = "Hyundai"
                        },
                        new
                        {
                            Id = 10,
                            Nombre = "Kia"
                        },
                        new
                        {
                            Id = 11,
                            Nombre = "Audi"
                        },
                        new
                        {
                            Id = 12,
                            Nombre = "Mazda"
                        },
                        new
                        {
                            Id = 13,
                            Nombre = "Subaru"
                        },
                        new
                        {
                            Id = 14,
                            Nombre = "Tesla"
                        },
                        new
                        {
                            Id = 15,
                            Nombre = "Volvo"
                        },
                        new
                        {
                            Id = 16,
                            Nombre = "Peugeot"
                        },
                        new
                        {
                            Id = 17,
                            Nombre = "Renault"
                        },
                        new
                        {
                            Id = 18,
                            Nombre = "Fiat"
                        },
                        new
                        {
                            Id = 19,
                            Nombre = "Jeep"
                        },
                        new
                        {
                            Id = 20,
                            Nombre = "Lexus"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
